# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org/
    - name: Cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: nodemodules-${{ hashFiles('yarn.lock') }}
        restore-keys: nodemodules-
    - name: Install Dependencies and prepare packages
      run: yarn install
      env:
        CI: true
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test


